### PR TITLE
Compile paper for dilevery

### PR DESCRIPTION
**Pull request by mmoanis**
We need to catch:
- Syntax errors
- Grammar mistakes
- Missing references
- Bad references
- Inconsistent parts

### CODE REVIEW

**Comment by MichaelSedrak** [comment]
1) Page 4 ACO first line (repition of "in the paths").
2) In other words, if pheromone did --(not)-- evaporate at all,
3) Page 5 ACO eequation description (tau of i,j) not (tau of i,s).
4) Another tau of i,s (should be tau of i,j) just before equation 6
5) Results section first paragraph [links!!!] is written should be removed and add citations to the 5 used algorithms
6) Results (th) t is super script h is not in 5th (fifth) .... and so on across all document
7) Results all durations in thousands should have commas after 3 digits.
8) Results table needs spacing adjustment (if possible)

**Comment by MichaelSedrak** [comment]
Sorry forgot to rename commit ---> Previous commit to solve 1,2,3,4

**Comment by MichaelSedrak** [comment]
Review comment ---> I think the document is consistent, clear and organized, i have seen a few syntax mistakes as mentioned above. fixed some of them. No obvious grammar mistakes i could detect

**Comment by mmoanis** [comment]
Did you update the PDF paper?

**Pull request merged**
